### ISSUE TITLE
Keep host variables

### ISSUE THREAD

**Issue by zuzuleinen** [benchkram/bob#136]
Currently, we have the possibility for a bob file to specify new env variables:

```yaml
variables:
  VAR_ONE: value
```

With new [hermetic mode](https://github.com/benchkram/bob/issues/131) functionality, we should also find a way to keep the values from local env. Similar to:

```shell
bob build --env VAR_ONE
```

but from bobfile.

This will allow a more ergonomic way to keep values without adding them to the cli commands

**Comment by Equanox** [comment]
Hmm that would mean you could create a bob.yaml which by default accepts value from the users system. I think this is the source of errors for "works on my machine". Therefore I'd rather not support this.

Closing feel free to reopen if this need more discussion.
