### ISSUE TITLE
`bob run` shows output only after initial build

### ISSUE THREAD

**Issue by Equanox** [benchkram/bob#15]
This blocks the TUI for a too long time

The commander should return without starting any long running tasks. Upstream code can then start the build after the TUI is started.

https://github.com/benchkram/bob/blob/36981b6f3c49f839e5678550a358f6faa8473daf/bob/run.go#L52

**Comment by zuzuleinen** [comment]
How to reproduce:

On the [example](https://github.com/benchkram/bob/tree/main/example/server-db) we have, change the build cmd to:

```yaml
    cmd: go build -o ./build/server main.go && sleep 10
```

Then run `bob run server`

**Comment by zuzuleinen** [comment]
I would personally remove also the [Commander](https://github.com/benchkram/bob/blob/main/pkg/ctl/commander.go#L15) interface in here as I don't see what the benefit of it is. I see it is just embedding another interface inside so not sure what behaviour is trying to abstract. I kept it as it is, after past discussions about interfaces in code reviews, I'm no longer sure what interface I can remove without breaking consistency within our team.
