### ISSUE TITLE
Make bob installable via Nix

### ISSUE THREAD

**Issue by zuzuleinen** [benchkram/bob#193]
Suggestion from [HN](https://news.ycombinator.com/item?id=32694064)

**Comment by lucperkins** [comment]
In addition to Nixpkgs, as you mentioned on HN, you could add a `flake.nix` to this repo with a `packages.default` that would enable people to run `nix profile install github:benchkram/bob`.

**Comment by zuzuleinen** [comment]
To get the value of **vendorSha256**

1. Uncomment `vendorSha256 = pkgs.lib.fakeSha256;` line 
2. Run nix-build.
3 You will get an error:

```shell
error: hash mismatch in fixed-output derivation '/nix/store/cvpva6ww5h4vy29b3zjrw9fymkfgi9kk-bob0.5.3-go-modules.drv':
         specified: sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=
            got:    sha256-BzlZiAXA8wQ7RU6N1knPYH/BDX1Ae+2+4pVJ41ecK7A=
```

The new value from got is your new `vendorSha256`.

**Comment by zuzuleinen** [comment]
### Testing

Some commands I run after deploying the `flake.nix` and `flake.lock`

## nix flake show

```shell
$  nix flake show  github:benchkram/bob
github:benchkram/bob/c9e8f2b2293089f16a3e77ced0d91c13a9fffff3
├───defaultPackage
│   ├───aarch64-darwin: package 'bob0.5.3'
│   ├───aarch64-linux: package 'bob0.5.3'
│   ├───x86_64-darwin: package 'bob0.5.3'
│   └───x86_64-linux: package 'bob0.5.3'
└───packages
    ├───aarch64-darwin
    │   └───bob: package 'bob0.5.3'
    ├───aarch64-linux
    │   └───bob: package 'bob0.5.3'
    ├───x86_64-darwin
    │   └───bob: package 'bob0.5.3'
    └───x86_64-linux
        └───bob: package 'bob0.5.3'
```

## nix profile install 

```shell
nix profile install  github:benchkram/bob
```

works correctly. Running `nix profile list` also shows bob in there:

```shell
4 github:benchkram/bob#defaultPackage.x86_64-linux github:benchkram/bob/c9e8f2b2293089f16a3e77ced0d91c13a9fffff3#defaultPackage.x86_64-linux /nix/store/fbk9dwr0nyjgsgcb00gv48hhdwc3awf7-bob0.5.3
```

## nix build

If I run `nix build github:benchkram/bob` in directory I get a `result` folder from where I can access bob with correct version:

```shell
$ ./result/bin/bob --version
bob version 0.5.3 linux/amd64
```

@lucperkins I hope this helps. [bob on nixpkgs](https://github.com/NixOS/nixpkgs/pull/189968) is almost read as well and when that is done I think I can close this issue.
