### ISSUE TITLE
Name clash

### ISSUE THREAD

**Issue by jkloetzke** [benchkram/bob#196]
I don't want to spoil the party but there is already a "bob" build tool -> https://github.com/BobBuildTool/bob. Incidentally the [Bob Build Tool](https://bobbuildtool.dev/) was invented with similar goals in mind. The main focus is on embedded systems development but it could certainly be used to build go apps in a Nix sandbox too.

Feel free to close the ticket. I don't mind too much about the name clash (after all, there are already other tools named bob out there). I just wanted to let you know...

**Comment by Equanox** [comment]
Hi Jan, thx for pointing it out. Agree it's a bit unfortunate but we have no plans to change the name.
