### ISSUE TITLE
Task duration is not displayed correctly for a failed task

### ISSUE THREAD

**Issue by puengel** [benchkram/bob#225]
![image](https://user-images.githubusercontent.com/3776893/192865468-2a3b451c-9fad-4102-9be5-2af175f6e912.png)

The task ran for over a minute. Maybe the task is closed too fast before gathering the duration result.

**Comment by zuzuleinen** [comment]
Steps to reproduce:

Have an invalid bobfile:

```yaml
build:
  build:
    cmd: echo "hello
```

Run `bob build`
