### ISSUE TITLE
bob init command

### ISSUE THREAD

**Issue by zuzuleinen** [benchkram/bob#265]
Maybe we should create a `bob init` which should similar to `git init`.

`bob init` creates a bob.yaml if it doesn't exist in the working directory with a build command which does an  `echo hello world`. Maybe the `nixpkgs` can be pinned to latest stable version

`bob init projectURL` should work similiar to `bob init` but also add a `project`.

If there is already a bob.yaml file inside working directory it should display a user error.

**Comment by rdnt** [comment]
We can already distinguish between a remote and a local project name, so maybe we can enforce a name for `bob init`.

**Comment by zuzuleinen** [comment]
> We can already distinguish between a remote and a local project name, so maybe we can enforce a name for `bob init`.

If we don't need a name for local projects, I wouldn't force users to do extra typing without benefits, would still keep it 'bob init' for them.
