### ISSUE TITLE
Git server 

### ISSUE THREAD

**Issue by gedw99** [benchkram/bob#3]
Lots of useful commands here and it also has a tui 

https://github.com/charmbracelet/soft-serve

can also Test against this server :)

**Comment by Equanox** [comment]
Wonderful idea :+1: , pretty sure we will look into it for testing. Currently we trying to simulate clones only from the filesystem system.

**Comment by gedw99** [comment]
Cool

i noticed you depend on git binary being installed 

their is pure golang.

but it’s quite a tall order to get all the primary hit functionality working with only golang

**Comment by gedw99** [comment]
Ah your using bubbletea 👍

**Comment by Equanox** [comment]
We tried https://github.com/go-git but it's performance was too bad for big repos, theirfore we had to use plain `git --porcelaine`. Still depending on "go-git" for some stuff.
