### ISSUE TITLE
Aqua versus nix

### ISSUE THREAD

**Issue by gedw99** [benchkram/bob#336]
Aqua is similar and runs  on windows too 

It has a registry and they can be cascaded in layers 

it’s golang based 

it has a proxy such that it’s like serverless but for binaries. So a calling program that expects a binary to be there won’t notice. Aqua I’ll pull the binary ( can have multiple versions of a binary too ) , and then direct the call through to the binary.

I like nix too :) 

Aqua might be another option . I changed to Aqua just because of its  ability to run anywhere.

https://github.com/aquaproj/aqua

https://github.com/aquaproj/aqua-proxy

And the actual registry 

https://github.com/aquaproj/aqua-registry

bobc can cache these too of course.. 

It might be a good option for integration into bon “ the builder “

**Comment by Equanox** [comment]
Actually aqua was our first take (#26 ) but we decided against it in favor of nix which offers a deeper integration especially for dependencies which require dynamic linking.

Closing this issue.
