### ISSUE TITLE
Bob run: Correct error message if blocking docker-containers are running

### ISSUE THREAD

**Issue by puengel** [benchkram/bob#85]
###Scenario
Have a docker container running which is using e.g. port 8080.
Have a run task which starts a container which also would use port 8080.

###Current behavior
Bob will just exit with either no message or a bad stack trace.

###Expected behavior
Proper user error parsed info from docker-compose message.

**Comment by Equanox** [comment]
Looks like this error is related only to this branch? The reason is the error not checked here.. https://github.com/benchkram/bob/blob/1fce501274598d5bf7242741d8d78a2f97442f0e/bobrun/run.go#L75 

Therefore the wrapper is initialized with a nil control.

Should be fixed when #84 is merged.

**Comment by Equanox** [comment]
Closing, feel free to reopen if this comes up again.
